categories:


  - main_category: "Women Clothing"
    sub_category: "Tops"
    brand: ""    
    max_count: 50


  - main_category: "Women Clothing"
    sub_category: "Denim"
    brand: "SHEIN"    
    max_count: 50 






