categories:


  - main_category: "Women Clothing"
    sub_category: "Wedding"
    brand: ""    
    max_count: 50


  - main_category: "Women Clothing"
    sub_category: "Party Wear"
    brand: ""    
    max_count: 50 






